### ISSUE TITLE
哈喽

### ISSUE THREAD

**Issue by ttzxl** [Baoji-Middle-School/Organization-Application#10]
- name:  shenyang
- grade:  2025届
- introduce yourself:  有点社恐，喜欢骑车，html，JS，但是想学后端，是菜鸟中的菜鸟，各位大佬多多包涵和知道啦

**Comment by suenyiyang** [comment]
Welcome! For backend development, you can start either with Golang, Python, Rust, Java or NodeJS according to your interest. Computer basis is also important for understanding how your program runs. Best wishes! 💚
