### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by wst426** [Baoji-Middle-School/Organization-Application#2]
我觉得要想吸引更多的人参与进来，需要先有一定的内容吸引。例如可以创建一个仓库，来介绍一些知识，比如：github 的使用、编辑器的配置、知识管理的方法、LaTeX 的使用等等；也可以做一些软件、网站、github 项目的分享。

先有一些基础、能够让大家参与进来的 repo，才能吸引到更多的人，否则大家更可能只是 star 一下，没有参与进来的欲望。

PS：建议  @fessorpro-30  公开一个邮箱，可以方便交流。

**Comment by suenyiyang** [comment]
收到！谢谢大佬建议！我近期尝试完善一下。请问大佬是宝中毕业生吗？是的话我拉您进来😁

**Comment by wst426** [comment]
name: 王劭彤
grade: 2018届
introduce yourself: 2018届宝中毕业生；西安理工大学本科生；菜鸡一枚。

**Comment by wst426** [comment]
我觉得要最开始应该多增加一些新手指南，多一些基础的教程。

可以参考一下[华南师大](https://0xffff.one/)的论坛和[清华大学的课程攻略](https://github.com/PKUanonym/REKCARC-TSC-UHT)

**Comment by suenyiyang** [comment]
邀请已发送。谢谢学长指点，我去参考一下😁
