### ISSUE TITLE
兴趣使然说两句

### ISSUE THREAD

**Issue by LiuPiPiPi** [Baoji-Middle-School/Organization-Application#3]
- name:  刘碧豪
- grade:  2017届
- introduce yourself:  西北工业大学软件工程

#### 集结宝中的程序员还真是个不错的想法
- 会持续关注，最近比较感兴趣建立自己的个人网站
- 感觉可以搞个小程序（相比于网站或者APP大家愿意多访问）
  - 核心功能还是围绕学习，分享学习经验、资料什么的
  - 业务目标就是不断扩大影响力，哪天能接广告了（补习班什么的）就是大成功
  - 当然只是建议，我也不知道现在高中生感兴趣什么

> 纯纯的兴趣使然，就是觉得平台不错，宝中的很多人都带着情怀的

**Comment by suenyiyang** [comment]
邀请已发送😁。感谢学长的宝贵建议。
我之前有想过做这几个东西：
- 足球、篮球班赛用户分享精彩集锦，公示裁判记录以及比赛成绩等的小程序。
- 官网。。。因为现在的官网有点太素了😂。
- 宝中人的论坛，为各届校友提供交流的平台。（这个论坛做成小程序也很方便，不用备案和搭建服务器👍学长建议很棒）。

学长如果想搭建个人博客的话，网上有很多基于Typecho或者Hexo搭建的博客，教程很全很细，我在用Typecho博客，希望能和学长多请教多交流。如果要从前端到后端自己完全开发出一个网站的话……我只能给您推荐一下阿里云服务器了，很便宜，24岁以下都算学生身份。一年一百出头就搞定。

感谢学长关注，我是电子科技大学沙河校区的软件工程专业的学生，以后要向您多请教😁！
