### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by suwhistle** [Baoji-Middle-School/Organization-Application#7]
- name:  梁宸鸣
- grade:  25届
- introduce yourself: 预计算机专业，有编程基础，前端还是后端目前不确定，请各位大佬多多指教

**Comment by ttzxl** [comment]
姓名：范珅瑒
年级：25届
自我介绍：对html感兴趣，但是想学后端，是一个菜鸟，请各位大佬多多包涵

**Comment by suenyiyang** [comment]
Invitation sent! I'm a frontend developer currently working in Bytedance Inc. in Chengdu. Welcome to exchange views! 💚
