### ISSUE TITLE
加零 申请加入组织

### ISSUE THREAD

**Issue by jiduoo** [Baoji-Middle-School/Organization-Application#8]
- name: 兰佳林（加零）
- grade:  2023届
- introduce yourself:  2023届宝中在读生；信息学奥赛选手（因为疫情未能参加NOIP；CSP-S一等奖）；算法；前端；游戏引擎（unity & ue5）；摄影爱好者；文学爱好者（科幻小说混了个陕西省青少年组一等奖）；python爬虫；Java略知；汇编略知；设计略知；MSSCTF混了个奖。喜欢的东西真的超级多，并不是样样精通，但是我还年轻对吧！

**Comment by jiduoo** [comment]
[贴个博客](https://www.cnblogs.com/addzero) https://www.cnblogs.com/addzero

**Comment by jiduoo** [comment]
也写过一版考试时钟 https://addexam.netlify.app/ 目前搁置了，之前运行过一段时间（主要是懒了）

**Comment by suenyiyang** [comment]
Great work bro! You're so excellent! Welcome and best wishes to you! If you are interested in frontend development in your college years, welcome to communicate with me! 💚
